# Simulation Configuration
simulation:
  engine:
    version: "1.0"
    precision_level: "standard"  # standard, high, extreme
    max_iterations: 10000
    convergence_threshold: 0.001

  computation:
    parallel_processing: true
    max_workers: 4
    chunk_size: 1000
    memory_limit_gb: 8

  validation:
    parameter_checking: true
    result_validation: true
    sanity_checks: true

  output:
    verbosity_level: "normal"  # quiet, normal, verbose, debug
    progress_tracking: true
    intermediate_results: false

physics:
  constants:
    gravitational_constant: 6.674e-11
    earth_mass_kg: 5.972e24
    earth_radius_km: 6371
    seconds_per_year: 31536000

  approximations:
    crater_scaling_law: "holsapple"
    atmospheric_model: "simplified"
    population_distribution: "uniform"
    economic_scaling: "linear"

models:
  asteroid:
    energy_calculation: "kinetic"
    crater_formation: "complex"
    atmospheric_effects: "enabled"
    tsunami_modeling: "simplified"

  pandemic:
    epidemic_model: "sir"  # SIR, SEIR, SIRV
    population_mixing: "homogeneous"
    intervention_effects: "basic"
    mutation_modeling: false

  climate:
    feedback_loops: "enabled"
    ocean_modeling: "simplified"
    ice_albedo_feedback: true
    carbon_cycle: "basic"

  volcano:
    ash_dispersal: "advection"
    climate_forcing: "aerosol"
    pyroclastic_flows: "energy_cone"

uncertainty:
  monte_carlo_samples: 1000
  confidence_intervals: [0.05, 0.95]
  sensitivity_analysis: true
  parameter_correlations: false
