name: Documentation

"on":
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

    - name: Install package
      run: |
        pip install -e .

    - name: Create docs directory if it doesn't exist
      run: |
        mkdir -p docs

    - name: Initialize Sphinx if needed
      run: |
        if [ ! -f docs/conf.py ]; then
          cd docs
          sphinx-quickstart -q --sep --project="ELES" --author="ELES Team" --release="1.0" --language="en" --makefile --batchfile --ext-autodoc --ext-viewcode .
        fi

    - name: Generate API documentation
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        sphinx-apidoc -o docs/source eles_core/ visualizations/

    - name: Build documentation
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        cd docs
        make html    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/_build/html/
  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Download documentation artifacts
      uses: actions/download-artifact@v4
      with:
        name: documentation
        path: docs/_build/html/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
